### ISSUE TITLE
Unable to find remote helper for https

### ISSUE THREAD

**Issue by 0jay** [davidjb/technicolor-hacks#4]
Hi
I'm a noob so probably doing something wrong but have tried to install git-http and get a 'cannot install package' error after process seems to be running fine.

when I try to 'git clone https://github.com/davidjb/technicolor-tg799vac-hacks.git' I get the 'unable to find remote helper' message.

Do you know what I can do to solve this?

Thanks for your time. 
Oscar

**Comment by davidjb** [comment]
Given you've mentioned `git-http`, it sounds like you might be trying to run the commands on an OpenWRT system like perhaps your modem.  If that's the case, the commands need to be run on a computer or separate device (eg not the modem), because you'll use the scripts and Python firmware flasher to remotely modify the modem.  I modified the README a little bit to clear that up (https://github.com/davidjb/technicolor-tg799vac-hacks#setup) if that's the case -- my writing did jump around a bit between commands on host and commands on the modem.

If you're running `git clone` on _another_ device that's not your modem, then it's a case of your git install probably doesn't have `https://` support available or is too old to support modern HTTPS etc.  In that case, either upgrade your environment or find another computer or device to run the scripts on or download the scripts manually from GitHub and unzip etc.

PR are welcome to help make the docs clearer :)

**Comment by flywire** [comment]
There are no releases so just select `Clone or Download` and `Download ZIP`. Script files are text so you could just copy and paste anyway.

**Comment by 0jay** [comment]
Thanks David, that's what I was trying to do.

I've actually rooted the modem which is running fine now in 17.2 but wanted to run your detox script to clean things up (I established most of the process via command line instructions as I couldn't work out how to use your scripts last time).

I'm trying again, attempting to begin with the detox script but am getting a no such directory message.

I'd previously downloaded your script successfully, am I doing something obviously stupid? If it's not obvious dont bother replying as I don't want to waste your time.

Thanks again.

**Comment by 0jay** [comment]
Allgood, I took flywire's advice and cut and pasted.

Is there no way to activate upnp without allowing this hardcoded password?

**Comment by davidjb** [comment]
@0jay Not sure I follow -- my scripts disable UPnP rather than activate or enable it.

**Comment by 0jay** [comment]
All good David, I've got it sorted.

Appreciate all the work you've put into this - it's your guide that got me there in the end, even if I was jumping all over the shop.

Thanks again for your time.
Oscar

**Comment by davidjb** [comment]
No worries, glad it was helpful.  If you've got any suggestions or improvements, PR are welcome.
