### ISSUE TITLE
import tkinter as tk error

### ISSUE THREAD

**Issue by linuxhackerguy** [davidjb/technicolor-hacks#8]
Maybe I am making some sort of rookie error but I keep getting when I go to run the python autoflashgui.py command

autoflashgui) root@kali:~/Desktop/technicolor/autoflashgui# python autoflashgui.py
Traceback (most recent call last):
  File "autoflashgui.py", line 13, in <module>
    import tkinter as tk
ImportError: No module named tkinter

thanks in advance.

**Comment by flywire** [comment]
Install tkinter.

**Comment by linuxhackerguy** [comment]
yeah I have tired that is there anything I have over looked ?

**Comment by kevdagoat** [comment]
Make sure you have run pip install tkinter not pip3

**Comment by linuxhackerguy** [comment]
yes I have done this. I cant even find it when I search for it using pip. There are a bunch of other ones ? Sorry to trouble you

**Comment by davidjb** [comment]
@linuxhackerguy It sounds like your Python isn't compiled or installed with Tk. For Kali, it looks you need to install the `python-tk` package (otherwise part of https://pkg.kali.org/pkg/python-stdlib-extensions).  If that package is already installed, then check which Python you're using, your library paths and so on.

**Comment by linuxhackerguy** [comment]
okay I will have a look at these things. Thanks for the guidance.

**Comment by linuxhackerguy** [comment]
okay sorted out the tkinter issue by downloading it from active state. https://www.activestate.com/products/tcl/downloads/
